[tool.pyright]
reportUnnecessaryTypeIgnoreComment = "warning"
reportAssertAlwaysTrue = "warning"
reportUnnecessaryIsInstance = "warning"
reportGeneralTypeIssues = "error"
pythonVersion = "3.8.10"
typeCheckingMode = "basic"
strictParameterNoneValue = false
include = [
    "cogs",
    "utils",
]
exclude = [
    "**/__pycache__",
    "build",
    "dist"
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]