name: Will it lint?

on: 
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  type-checking:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.x']
    name: Type Checking + Linting ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/venv
          key: ${{ matrix.os }}-pip-${{ env.cache-name }}-${{ hashfiles('requirements.txt') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m venv ~/venv
          . ~/venv/bin/activate
          python -m pip install --upgrade pip
          pip install flake8
          pip install -U -r requirements.txt

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check pyright
        run: |
          npm install pyright
          cd "$GITHUB_WORKSPACE"
          source ~/venv/bin/activate
          npx pyright --venv-path ~/venv

      - name: Lint with flake8
        run: |
          . ~/venv/bin/activate
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The Github editor is 127 chars wide
          flake8 . --count --statistics --config=./setup.cfg
