name: Pytest

on: 
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  type-checking:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.x']
    name: Type Checking + Linting ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/venv
          key: ${{ matrix.os }}-pip-${{ env.cache-name }}-${{ hashfiles('requirements.txt') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m venv ~/venv
          . ~/venv/bin/activate
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio
          pip install -U -r requirements.txt

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run tests
        shell: bash
        run: |
          . ~/venv/bin/activate
          PYTHONPATH="$(pwd)" pytest -vs
